/**
 * One-off data migration: Neon (Postgres) -> Cloudflare D1 (SQLite).
 *
 * Reads every table from the OLD Neon database and emits a SQL file of INSERT
 * statements compatible with D1, transforming Postgres-only shapes:
 *   - text[] array columns        -> JSON strings  (e.g. productImages)
 *   - json/jsonb columns          -> JSON strings  (campaigns.layout/pageLayout)
 *   - booleans                    -> 1 / 0
 *   - Date/timestamps             -> ISO 8601 strings
 *
 * Usage:
 *   1) Point NEON_DATABASE_URL at the old Postgres DB (or reuse DATABASE_URL).
 *   2) npx tsx scripts/migrate-neon-to-d1.ts
 *   3) wrangler d1 execute sleep-sheet-reborn --remote --file=./prisma/data-d1.sql
 *      (use --local to load a local dev DB instead)
 *
 * NOTE: D1's `execute --file` has size limits. For very large datasets, split
 * the output or import per-table.
 */
import "dotenv/config";
import { neon } from "@neondatabase/serverless";
import { writeFileSync } from "node:fs";
import path from "node:path";

const CONN = process.env.NEON_DATABASE_URL || process.env.DATABASE_URL;
if (!CONN) {
  console.error("Set NEON_DATABASE_URL (or DATABASE_URL) to the old Neon connection string.");
  process.exit(1);
}

const sql = neon(CONN);

// Insertion order respects foreign keys (parents first).
const TABLES = [
  '"User"',
  '"Category"',
  '"products"',
  '"shipping_methods"',
  '"orders"',
  '"order_items"',
  '"payments"',
  '"order_timeline_events"',
  '"carts"',
  '"cart_items"',
  '"wishlists"',
  '"wishlist_items"',
  '"product_reviews"',
  '"product_specifications"',
  '"campaigns"',
  '"Testimonial"',
  '"OTPVerification"',
  '"site_settings"',
];

function toSqlValue(v: unknown): string {
  if (v === null || v === undefined) return "NULL";
  if (typeof v === "boolean") return v ? "1" : "0";
  if (typeof v === "number") return Number.isFinite(v) ? String(v) : "NULL";
  if (v instanceof Date) return `'${v.toISOString()}'`;
  if (Array.isArray(v) || typeof v === "object") {
    return `'${JSON.stringify(v).replace(/'/g, "''")}'`;
  }
  // string (covers Postgres returning timestamps/json as text too)
  return `'${String(v).replace(/'/g, "''")}'`;
}

async function main() {
  const out: string[] = [
    "PRAGMA defer_foreign_keys = TRUE;",
    "-- Generated by scripts/migrate-neon-to-d1.ts",
  ];

  for (const table of TABLES) {
    const rows = (await sql.query(`SELECT * FROM ${table}`)) as Record<string, unknown>[];
    if (!rows.length) {
      out.push(`-- ${table}: 0 rows`);
      continue;
    }
    const cols = Object.keys(rows[0]);
    const colList = cols.map((c) => `"${c}"`).join(", ");
    out.push(`-- ${table}: ${rows.length} rows`);
    for (const row of rows) {
      const vals = cols.map((c) => toSqlValue(row[c])).join(", ");
      out.push(`INSERT INTO ${table} (${colList}) VALUES (${vals});`);
    }
  }

  const target = path.join("prisma", "data-d1.sql");
  writeFileSync(target, out.join("\n") + "\n");
  console.log(`Wrote ${target} (${out.length} lines).`);
}

main().catch((e) => {
  console.error(e);
  process.exit(1);
});
